### ISSUE TITLE
Change requires refresh to I minute before expiration? (Maybe longer)

### ISSUE THREAD

**Issue by nehayward** [AlaskaAirlines/atom#4]
Hey @michaelbabiy this might be the reason we are seeing an issue with sending invalid tokens. In the event that the token will expire within milliseconds, we could potentially send an invalid token, by the time it reaches the endpoint.

https://github.com/AlaskaAirlines/atom/blob/b0b60642323294a1595eb53e61fd092e3621b212/Framework/Atom/Models/Atom%2BTokenCredential%2BAdditions.swift#L21

**Comment by michaelbabiy** [comment]
# Reply
Hey Nick,

When writing this implementation I didn’t want to assume I can safely subtract any number of seconds / minutes from the expiration date of the issued access token (for example, Alaska’s QA environment issues an access token that’s only good for 2 minutes. It is possible to have a short lived access token that’s only valid for 1 minute).

Adjusting expiration time is something a client can do when implementing `TokenCredentialWritable`. For example, assuming you have something like this written:

```swift
final class TokenManager: TokenCredentialWritable {
    /// A proxy property for writing and reading token values from the iOS keychain.
    var tokenCredential: Atom.TokenCredential {
        get { authentication.ssoCredential.token }
        set { authentication.ssoCredential = newValue.ssoCredential }
    }
}
```

where `ssoCredential`  is an extension on `Atom.TokenCredential` type:

```swift
extension Atom.TokenCredential {
    /// Returns new sso credential initialized from `TokenCredential` instance.
    var ssoCredential: Authentication.SSOCredential {
        .init(accessToken: accessToken, expiresIn: expiresIn, refreshToken: refreshToken)
    }
}
```

It is here that you can subtract n-number of seconds from `expiresIn` before writing new value to the iOS keychain. So, assuming your token is valid for 15 minutes and you would like to give yourself an extra minute, your implementation could look something like this:

```swift
extension Atom.TokenCredential {
    /// Returns new sso credential initialized from `TokenCredential` instance.
    var ssoCredential: Authentication.SSOCredential {
        .init(accessToken: accessToken, expiresIn: expiresIn - 60, refreshToken: refreshToken)
    }
}
```

Cheers!
